
library(ggplot2)
library(grid)
library(gridExtra)
library(dplyr)
#library("ggsci")
library(RColorBrewer)
library(cowplot)
library(ggalt)

###################################################################### epistasis level #############################################################

list.VariantType<-c(0,-0.0001,-0.001,-0.01,-0.1)
list.ep_level<-c(0,0.0001,0.001,0.01)

data.model1_h05_diffEp_N10000.maxdac2.mindac2.samples1000.cor=read.table(file="../data/fig2_data.model1_h05_diffEp_N10000.maxdac2.mindac2.samples1000.cor")
data.model2_h05_diffEp_N10000.maxdac2.mindac2.samples1000.cor=read.table(file="../data/fig2_data.model2_h05_diffEp_N10000.maxdac2.mindac2.samples1000.cor")
data.model3_h05_diffEp_N10000.maxdac2.mindac2.samples1000.cor=read.table(file="../data/fig2_data.model3_h05_diffEp_N10000.maxdac2.mindac2.samples1000.cor")

###################################################################### N  #############################################################

data.N1_h05_diffM.maxdac2.mindac2.cor=read.table(file="../data/fig2_data.N1_h05_diffM.maxdac2.mindac2.cor")
data.N2_h05_diffM.maxdac2.mindac2.cor=read.table(file="../data/fig2_data.N2_h05_diffM.maxdac2.mindac2.cor")
data.N3_h05_diffM.maxdac2.mindac2.cor=read.table(file="../data/fig2_data.N3_h05_diffM.maxdac2.mindac2.cor")

###################################################################### bottleneck diff_time  #############################################################

data.bn0_difftime.cor=read.table(file="../data/fig2_data.bn0_difftime.cor")
data.bn1_difftime.cor=read.table(file="../data/fig2_data.bn1_difftime.cor")
data.bn2_difftime.cor=read.table(file="../data/fig2_data.bn2_difftime.cor")

######################################################################################## distance #########################################################

distance=c(10,100,1000)

list.model1_distance=list()
list.model1_distance_null=list()
nn=0;for(ii in 1:length(distance)){for(jj in 1:19){nn=nn+1;list.model1_distance[[nn]]=na.omit(cbind(read.table(paste0("../../20220816/inbrief_distance/model1_h05_r08_N10000.maxdac",jj+1,".mindac2.samples1000.distance",distance[ii]),header=TRUE),distance=rep(distance[ii]),maxdac=rep(jj+1)))}}
nn=0;for(jj in 1:19){nn=nn+1;list.model1_distance_null[[nn]]=na.omit(cbind(read.table(paste0("../../20220816/inbrief/model1_h05_r08_N10000.maxdac",jj+1,".mindac2.samples1000"),header=TRUE),distance=rep(0),maxdac=rep(jj+1)))}

data.list.model1_distance.cor=matrix(nrow=length(list.VariantType)*length(list.model1_distance),ncol=6);nn=0;for(vv in list.VariantType){for(ii in 1:length(list.model1_distance)){nn=nn+1;data.list.model1_distance.cor[nn,1]=vv;data.list.model1_distance.cor[nn,2]=list.model1_distance[[ii]][1,12];data.list.model1_distance.cor[nn,3]=list.model1_distance[[ii]][1,13];if(ii%%19>0){aa=ii%%19}else{aa=19};data.list.model1_distance.cor[nn,4]=mean(list.model1_distance[[ii]][which(list.model1_distance[[ii]][,1]==vv),8]-list.model1_distance_null[[aa]][which(list.model1_distance_null[[aa]][,1]==vv),8]);data.list.model1_distance.cor[nn,5]=sd(list.model1_distance[[ii]][which(list.model1_distance[[ii]][,1]==vv),8]-list.model1_distance_null[[aa]][which(list.model1_distance_null[[aa]][,1]==vv),8]);data.list.model1_distance.cor[nn,6]=length(list.model1_distance[[ii]][which(list.model1_distance[[ii]][,1]==vv),8]-list.model1_distance_null[[aa]][which(list.model1_distance_null[[aa]][,1]==vv),8])}};colnames(data.list.model1_distance.cor)<-c("VariantType","distance","maxdac","Mean","Sd","Nruns");data.list.model1_distance.cor<-data.frame(data.list.model1_distance.cor)

list.model2_distance=list()
list.model2_distance_null=list()
nn=0;for(ii in 1:length(distance)){for(jj in 1:19){nn=nn+1;list.model2_distance[[nn]]=na.omit(cbind(read.table(paste0("../../20220816/inbrief_distance/model2_h05_r08_N10000.maxdac",jj+1,".mindac2.samples1000.distance",distance[ii]),header=TRUE),distance=rep(distance[ii]),maxdac=rep(jj+1)))}}
nn=0;for(jj in 1:19){nn=nn+1;list.model2_distance_null[[nn]]=na.omit(cbind(read.table(paste0("../../20220816/inbrief/model2_h05_r08_N10000.maxdac",jj+1,".mindac2.samples1000"),header=TRUE),distance=rep(0),maxdac=rep(jj+1)))}
data.list.model2_distance.cor=matrix(nrow=length(list.VariantType)*length(list.model2_distance),ncol=6);nn=0;for(vv in list.VariantType){for(ii in 1:length(list.model2_distance)){nn=nn+1;data.list.model2_distance.cor[nn,1]=vv;data.list.model2_distance.cor[nn,2]=list.model2_distance[[ii]][1,12];data.list.model2_distance.cor[nn,3]=list.model2_distance[[ii]][1,13];if(ii%%19>0){aa=ii%%19}else{aa=19};data.list.model2_distance.cor[nn,4]=mean(list.model2_distance[[ii]][which(list.model2_distance[[ii]][,1]==vv),8]-list.model2_distance_null[[aa]][which(list.model2_distance_null[[aa]][,1]==vv),8]);data.list.model2_distance.cor[nn,5]=sd(list.model2_distance[[ii]][which(list.model2_distance[[ii]][,1]==vv),8]-list.model2_distance_null[[aa]][which(list.model2_distance_null[[aa]][,1]==vv),8]);data.list.model2_distance.cor[nn,6]=length(list.model2_distance[[ii]][which(list.model2_distance[[ii]][,1]==vv),8]-list.model2_distance_null[[aa]][which(list.model2_distance_null[[aa]][,1]==vv),8])}};colnames(data.list.model2_distance.cor)<-c("VariantType","distance","maxdac","Mean","Sd","Nruns");data.list.model2_distance.cor<-data.frame(data.list.model2_distance.cor)

list.model3_distance=list()
list.model3_distance_null=list()
nn=0;for(ii in 1:length(distance)){for(jj in 1:19){nn=nn+1;list.model3_distance[[nn]]=na.omit(cbind(read.table(paste0("../../20220816/inbrief_distance/model3_h05_r08_N10000.maxdac",jj+1,".mindac2.samples1000.distance",distance[ii]),header=TRUE),distance=rep(distance[ii]),maxdac=rep(jj+1)))}}
nn=0;for(jj in 1:19){nn=nn+1;list.model3_distance_null[[nn]]=na.omit(cbind(read.table(paste0("../../20220816/inbrief/model3_h05_r08_N10000.maxdac",jj+1,".mindac2.samples1000"),header=TRUE),distance=rep(0),maxdac=rep(jj+1)))}
data.list.model3_distance.cor=matrix(nrow=length(list.VariantType)*length(list.model3_distance),ncol=6);nn=0;for(vv in list.VariantType){for(ii in 1:length(list.model3_distance)){nn=nn+1;data.list.model3_distance.cor[nn,1]=vv;data.list.model3_distance.cor[nn,2]=list.model3_distance[[ii]][1,12];data.list.model3_distance.cor[nn,3]=list.model3_distance[[ii]][1,13];if(ii%%19>0){aa=ii%%19}else{aa=19};data.list.model3_distance.cor[nn,4]=mean(list.model3_distance[[ii]][which(list.model3_distance[[ii]][,1]==vv),8]-list.model3_distance_null[[aa]][which(list.model3_distance_null[[aa]][,1]==vv),8]);data.list.model3_distance.cor[nn,5]=sd(list.model3_distance[[ii]][which(list.model3_distance[[ii]][,1]==vv),8]-list.model3_distance_null[[aa]][which(list.model3_distance_null[[aa]][,1]==vv),8]);data.list.model3_distance.cor[nn,6]=length(list.model3_distance[[ii]][which(list.model3_distance[[ii]][,1]==vv),8]-list.model3_distance_null[[aa]][which(list.model3_distance_null[[aa]][,1]==vv),8])}};colnames(data.list.model3_distance.cor)<-c("VariantType","distance","maxdac","Mean","Sd","Nruns");data.list.model3_distance.cor<-data.frame(data.list.model3_distance.cor)

data.list.model1_distance.cor=read.table(file="../data/fig2_data.list.model1_distance.cor")
data.list.model2_distance.cor=read.table(file="../data/fig2_data.list.model2_distance.cor")
data.list.model3_distance.cor=read.table(file="../data/fig2_data.list.model3_distance.cor")

############################################################################ next, 三合一 ################################################################################

fig2_h05_mindac2_maxdac2_model1<-ggplot(data.model1_h05_diffEp_N10000.maxdac2.mindac2.samples1000.cor,aes(x=factor(VariantType,levels=list.VariantType),y=as.numeric(Mean)*100,group=ep_level,colour=factor(ep_level,levels=c(0,3,2))))+geom_xspline(spline_shape=-0.6,aes(colour=factor(ep_level,levels=c(0,3,2))))+geom_errorbar(aes(ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(Nruns))*100,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(Nruns))*100),width=0.2)+theme_classic()+labs(x="",y="LDcor (×100)",title="A")+theme(legend.position = "bottom",legend.key.size=unit(10,"pt"),text=element_text(family="serif",size=12),axis.text=element_text(size=10,color="black"),legend.text=element_text(size=10),legend.title=element_text(size=10))+scale_x_discrete(breaks=list.VariantType,labels=c(0,expression(10^-4),expression(10^-3),expression(10^-2),expression(10^-1)))+geom_point(size=0.8)+scale_y_continuous(expand=c(0,0),limits=c(0,0.6),breaks=seq(0,0.6,0.1))+geom_hline(yintercept=0,lty=2,size=0.8,color="gray")+annotate("text",x="0",y=-0.1,label="Model 1")+scale_color_manual(breaks=c(0,3,2),labels=c(0,expression(10^-3),expression(10^-2)),values=c("#9ECAE1","#AE017E","#DE2D26"),name="El")
fig2_h05_mindac2_maxdac2_model3<-ggplot(data.model3_h05_diffEp_N10000.maxdac2.mindac2.samples1000.cor,aes(x=factor(VariantType,levels=list.VariantType),y=as.numeric(Mean)*100,group=ep_level,colour=factor(ep_level,levels=c(0,3,2))))+geom_xspline(spline_shape=-0.6,aes(colour=factor(ep_level,levels=c(0,3,2))))+geom_errorbar(aes(ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(Nruns))*100,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(Nruns))*100),width=0.2)+theme_classic()+labs(x="",y="LDcor (×100)",title="A")+theme(legend.position = "bottom",legend.key.size=unit(10,"pt"),text=element_text(family="serif",size=12),axis.text=element_text(size=10,color="black"),legend.text=element_text(size=10),legend.title=element_text(size=10))+scale_x_discrete(breaks=list.VariantType,labels=c(0,expression(10^-4),expression(10^-3),expression(10^-2),expression(10^-1)))+geom_point(size=0.8)+scale_y_continuous(expand=c(0,0),limits=c(0,0.6),breaks=seq(0,0.6,0.1))+geom_hline(yintercept=0,lty=2,size=0.8,color="gray")+annotate("text",x="0",y=-0.1,label="Model 2")+scale_color_manual(breaks=c(0,3,2),labels=c(0,expression(10^-3),expression(10^-2)),values=c("#9ECAE1","#AE017E","#DE2D26"),name="El")
fig2_h05_mindac2_maxdac2_model2<-ggplot(data.model2_h05_diffEp_N10000.maxdac2.mindac2.samples1000.cor,aes(x=factor(VariantType,levels=list.VariantType),y=as.numeric(Mean)*100,group=ep_level,colour=factor(ep_level,levels=c(0,3,2))))+geom_xspline(spline_shape=-0.6,aes(colour=factor(ep_level,levels=c(0,3,2))))+geom_errorbar(aes(ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(Nruns))*100,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(Nruns))*100),width=0.2)+theme_classic()+labs(x="Selection coefficient",y="LDcor (×100)",title="A")+theme(legend.position = "bottom",legend.key.size=unit(10,"pt"),text=element_text(family="serif",size=12),axis.text=element_text(size=10,color="black"),legend.text=element_text(size=10),legend.title=element_text(size=10))+scale_x_discrete(breaks=list.VariantType,labels=c(0,expression(10^-4),expression(10^-3),expression(10^-2),expression(10^-1)))+geom_point(size=0.8)+scale_y_continuous(expand=c(0,0),limits=c(0,0.6),breaks=seq(0,0.6,0.1))+geom_hline(yintercept=0,lty=2,size=0.8,color="gray")+annotate("text",x="0",y=-0.1,label="Model 3")+scale_color_manual(breaks=c(0,3,2),labels=c(0,expression(10^-3),expression(10^-2)),values=c("#9ECAE1","#AE017E","#DE2D26"),name="El")
grid.arrange(fig2_h05_mindac2_maxdac2_model1,fig2_h05_mindac2_maxdac2_model3,fig2_h05_mindac2_maxdac2_model2)

fig3_h05_mindac2_maxdac2_cor_N1_1<-ggplot(data.N1_h05_diffM.maxdac2.mindac2.cor,aes(x=factor(VariantType,levels=list.VariantType),y=as.numeric(Mean)*100,group=Model,colour=as.factor(Model)))+geom_errorbar(aes(ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(Nruns))*100,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(Nruns))*100),width=0.2)+geom_xspline(spline_shape=-0.6,aes(colour=as.factor(Model)))+theme_classic()+labs(x="",y="LDcor (×100)",title="B")+ theme(legend.position = "bottom",legend.key.size=unit(10,"pt"),text=element_text(family="serif",size=12),axis.text=element_text(size=10,color="black"),legend.text=element_text(size=10),legend.title=element_text(size=10))+scale_x_discrete(breaks=list.VariantType,labels=c(0,expression(10^-4),expression(10^-3),expression(10^-2),expression(10^-1)))+geom_point(size=0.8)+scale_y_continuous(expand=c(0,0),limits=c(0,0.6),breaks=seq(0,0.6,0.1))+geom_hline(yintercept=0,lty=2,size=0.8,color="gray")+annotate("text",x="0",y=-0.1,label="10000 in evolving and 1000 in calculating")+scale_color_manual(values=c("#9ECAE1","#AE017E","#DE2D26"),name="Model")
fig3_h05_mindac2_maxdac2_cor_N2_1<-ggplot(data.N2_h05_diffM.maxdac2.mindac2.cor,aes(x=factor(VariantType,levels=list.VariantType),y=as.numeric(Mean)*100,group=Model,colour=as.factor(Model)))+geom_errorbar(aes(ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(Nruns))*100,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(Nruns))*100),width=0.2)+geom_xspline(spline_shape=-0.6,aes(colour=as.factor(Model)))+theme_classic()+labs(x="",y="LDcor (×100)",title="")+theme(legend.position = "bottom",legend.key.size=unit(10,"pt"),text=element_text(family="serif",size=12),axis.text=element_text(size=10,color="black"),legend.text=element_text(size=10),legend.title=element_text(size=10))+scale_x_discrete(breaks=list.VariantType,labels=c(0,expression(10^-4),expression(10^-3),expression(10^-2),expression(10^-1)))+geom_point(size=0.8)+scale_y_continuous(expand=c(0,0),limits=c(0,3.6),breaks=seq(0,3.6,0.6))+geom_hline(yintercept=0,lty=2,size=0.8,color="gray")+annotate("text",x="0",y=-1,label="1000 in evolving and 1000 in calculating")+scale_color_manual(values=c("#9ECAE1","#AE017E","#DE2D26"),name="Model")
fig3_h05_mindac2_maxdac2_cor_N3_1<-ggplot(data.N3_h05_diffM.maxdac2.mindac2.cor,aes(x=factor(VariantType,levels=list.VariantType),y=as.numeric(Mean)*100,group=Model,colour=as.factor(Model)))+geom_errorbar(aes(ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(Nruns))*100,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(Nruns))*100),width=0.2)+geom_xspline(spline_shape=-0.6,aes(colour=as.factor(Model)))+theme_classic()+labs(x="Selection coefficient",y="LDcor (×100)",title="")+ theme(legend.position = "bottom",legend.key.size=unit(10,"pt"),text=element_text(family="serif",size=12),axis.text=element_text(size=10,color="black"),legend.text=element_text(size=10),legend.title=element_text(size=10))+scale_x_discrete(breaks=list.VariantType,labels=c(0,expression(10^-4),expression(10^-3),expression(10^-2),expression(10^-1)))+geom_point(size=0.8)+scale_y_continuous(expand=c(0,0),limits=c(0,36),breaks=seq(0,36,6))+geom_hline(yintercept=0,lty=2,size=0.8,color="gray")+annotate("text",x="0",y=-10,label="100 in evolving and 100 in calculating")+scale_color_manual(values=c("#9ECAE1","#AE017E","#DE2D26"),name="Model")

fig2_bn0_difftime<-ggplot(data.bn0_difftime.cor,aes(x=factor(VariantType,levels=list.VariantType),y=as.numeric(Mean)*100,group=time,colour=factor(time)))+geom_xspline(spline_shape=-0.6,aes(colour=factor(time)))+geom_errorbar(aes(ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(Nruns))*100,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(Nruns))*100),width=0.2)+theme_classic()+labs(x="",y="LDcor (×100)",title="C")+theme(legend.position = "bottom",legend.key.size=unit(10,"pt"),text=element_text(family="serif",size=12),axis.text=element_text(size=10,color="black"),legend.text=element_text(size=10),legend.title=element_text(size=10))+scale_x_discrete(breaks=list.VariantType,labels=c(0,expression(10^-4),expression(10^-3),expression(10^-2),expression(10^-1)))+geom_point(size=0.8)+scale_y_continuous(expand=c(0,0),limits=c(-1,5),breaks=seq(-1,5,1))+annotate("text",x="0",y=-0.1,label="Model 1")+scale_color_manual(breaks=c(1,3,5,"01","00"),values=c("#9ECAE1","#AE017E","#DE2D26","#CCCCCC","#636363"),name="Time")
fig2_bn1_difftime<-ggplot(data.bn1_difftime.cor,aes(x=factor(VariantType,levels=list.VariantType),y=as.numeric(Mean)*100,group=time,colour=factor(time)))+geom_xspline(spline_shape=-0.6,aes(colour=factor(time)))+geom_errorbar(aes(ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(Nruns))*100,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(Nruns))*100),width=0.2)+theme_classic()+labs(x="",y="LDcor (×100)",title="")+theme(legend.position = "bottom",legend.key.size=unit(10,"pt"),text=element_text(family="serif",size=12),axis.text=element_text(size=10,color="black"),legend.text=element_text(size=10),legend.title=element_text(size=10))+scale_x_discrete(breaks=list.VariantType,labels=c(0,expression(10^-4),expression(10^-3),expression(10^-2),expression(10^-1)))+geom_point(size=0.8)+scale_y_continuous(expand=c(0,0),limits=c(-1,8),breaks=seq(-1,8,1.5))+annotate("text",x="0",y=-0.1,label="Model 1")+scale_color_manual(breaks=c(1,3,5,"01","00"),values=c("#9ECAE1","#AE017E","#DE2D26","#CCCCCC","#636363"),name="Time")
fig2_bn2_difftime<-ggplot(data.bn2_difftime.cor,aes(x=factor(VariantType,levels=list.VariantType),y=as.numeric(Mean)*100,group=time,colour=factor(time)))+geom_xspline(spline_shape=-0.6,aes(colour=factor(time)))+geom_errorbar(aes(ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(Nruns))*100,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(Nruns))*100),width=0.2)+theme_classic()+labs(x="",y="LDcor (×100)",title="")+theme(legend.position = "bottom",legend.key.size=unit(10,"pt"),text=element_text(family="serif",size=12),axis.text=element_text(size=10,color="black"),legend.text=element_text(size=10),legend.title=element_text(size=10))+scale_x_discrete(breaks=list.VariantType,labels=c(0,expression(10^-4),expression(10^-3),expression(10^-2),expression(10^-1)))+geom_point(size=0.8)+scale_y_continuous(expand=c(0,0),limits=c(-1,11),breaks=seq(-1,11,2))+annotate("text",x="0",y=-0.1,label="Model 1")+scale_color_manual(breaks=c(1,3,5,"01","00"),values=c("#9ECAE1","#AE017E","#DE2D26","#CCCCCC","#636363"),name="Time")

figS11_model1_cor<-ggplot(data.list.model1_distance.cor[which(data.list.model1_distance.cor[,1]=="0"),],aes(x=maxdac,y=as.numeric(Mean)*10000,group=distance,colour=as.factor(distance)))+geom_ribbon(aes(fill=factor(distance),ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(Nruns))*10000,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(Nruns))*10000),size=0,alpha=0.2)+geom_xspline(spline_shape=-0.6,aes(colour=as.factor(distance)))+theme_classic()+labs(x="",y="LDcor*10000 (s=0)",title="D.Model 1")+ theme(text=element_text(family="serif",size=11),axis.text=element_text(size=11,color="black"),legend.text=element_text(size=11),legend.title=element_text(size=11),legend.key.size=unit(11,"pt"),legend.key.width=unit(11,"pt"),legend.position = "bottom",plot.title = element_text(size=11))+geom_point(size=0.8)+scale_color_manual(name="Distance",limits=c(10,100,1000),values=c("#AE017E","#9ECAE1","#DE2D26"))+geom_hline(yintercept=0,lty=2,size=0.5,color="gray")+scale_fill_manual(name="Distance",limits=c(10,100,1000),values=c("#AE017E","#9ECAE1","#DE2D26"))+scale_y_continuous(expand=c(0,0),limits=c(-3.6,0.6),breaks=seq(-3.6,0.6,0.7))+scale_x_continuous(expand=c(0,0),limits=c(1,21),breaks=seq(2,20,2))
figS11_model2_cor<-ggplot(data.list.model2_distance.cor[which(data.list.model2_distance.cor[,1]=="0"),],aes(x=maxdac,y=as.numeric(Mean)*10000,group=distance,colour=as.factor(distance)))+geom_ribbon(aes(fill=factor(distance),ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(Nruns))*10000,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(Nruns))*10000),size=0,alpha=0.2)+geom_xspline(spline_shape=-0.6,aes(colour=as.factor(distance)))+theme_classic()+labs(x="",y="",title="Model 2")+ theme(text=element_text(family="serif",size=11),axis.text=element_text(size=11,color="black"),legend.text=element_text(size=11),legend.title=element_text(size=11),legend.key.size=unit(11,"pt"),legend.key.width=unit(11,"pt"),legend.position = "bottom",plot.title = element_text(size=11))+geom_point(size=0.8)+scale_color_manual(name="Distance",limits=c(10,100,1000),values=c("#AE017E","#9ECAE1","#DE2D26"))+geom_hline(yintercept=0,lty=2,size=0.5,color="gray")+scale_fill_manual(name="Distance",limits=c(10,100,1000),values=c("#AE017E","#9ECAE1","#DE2D26"))+scale_y_continuous(expand=c(0,0),limits=c(-1.8,0.6),breaks=seq(-1.8,0.6,0.4))+scale_x_continuous(expand=c(0,0),limits=c(1,21),breaks=seq(2,20,2))
figS11_model3_cor<-ggplot(data.list.model3_distance.cor[which(data.list.model3_distance.cor[,1]=="0"),],aes(x=maxdac,y=as.numeric(Mean)*10000,group=distance,colour=as.factor(distance)))+geom_ribbon(aes(fill=factor(distance),ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(Nruns))*10000,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(Nruns))*10000),size=0,alpha=0.2)+geom_xspline(spline_shape=-0.6,aes(colour=as.factor(distance)))+theme_classic()+labs(x="Max derived allele count",y="",title="Model 3")+ theme(text=element_text(family="serif",size=11),axis.text=element_text(size=11,color="black"),legend.text=element_text(size=11),legend.title=element_text(size=11),legend.key.size=unit(11,"pt"),legend.key.width=unit(11,"pt"),legend.position = "bottom",plot.title = element_text(size=11))+geom_point(size=0.8)+scale_color_manual(name="Distance",limits=c(10,100,1000),values=c("#AE017E","#9ECAE1","#DE2D26"))+geom_hline(yintercept=0,lty=2,size=0.5,color="gray")+scale_fill_manual(name="Distance",limits=c(10,100,1000),values=c("#AE017E","#9ECAE1","#DE2D26"))+scale_y_continuous(expand=c(0,0),limits=c(-1.8,0.6),breaks=seq(-1.8,0.6,0.4))+scale_x_continuous(expand=c(0,0),limits=c(1,21),breaks=seq(2,20,2))

fig2<-plot_grid(fig2_h05_mindac2_maxdac2_model1,fig2_bn0_difftime,fig3_h05_mindac2_maxdac2_cor_N1_1,fig2_h05_mindac2_maxdac2_model3,fig2_bn1_difftime,fig3_h05_mindac2_maxdac2_cor_N2_1,fig2_h05_mindac2_maxdac2_model2,fig2_bn2_difftime,fig3_h05_mindac2_maxdac2_cor_N3_1,figS11_model1_cor,figS11_model3_cor,figS11_model2_cor,ncol=3,align="vh")
ggsave("fig2.ep_gd_dis.se.svg",fig2,width = 9, height = 12)

