
library(ggplot2)
library(grid)
library(gridExtra)
library(dplyr)
#library("ggsci")
library(RColorBrewer)
library(cowplot)
library(ggpubr)
library(ggalt)


list.VariantType<-c(0,-0.0001,-0.001)
list.VariantType_1<-c(0,expression(10^-4),expression(10^-3))

data.list.goldenSM.cor=read.table(file="../data/fig5_data.list.goldenSM.cor")
data.list.goldenSM.corabs=read.table(file="../data/fig5_data.list.goldenSM.corabs")
data.list.panda.cor=read.table(file="../data/fig5_data.list.panda.cor")
data.list.panda.corabs=read.table(file="../data/fig5_data.list.panda.corabs")
data.list.pandaSim.cor=read.table(file="../data/fig5_data.list.pandaSim.cor")
data.list.pandaSim.corabs=read.table(file="../data/fig5_data.list.pandaSim.corabs")

fig5_goldenSM_cor_mdac<-ggplot(data.list.goldenSM.cor,aes(x=as.numeric(mdac),y=as.numeric(Mean)*100,group=VariantType,colour=factor(VariantType,levels=list.VariantType),fill=factor(VariantType,levels=list.VariantType)))+geom_line()+theme_classic()+labs(x="",y="LDcor (×100)",title="A.GoldenSM")+theme(text=element_text(family="serif",size=12),axis.text=element_text(size=10,color="black"),legend.text=element_text(size=10),legend.title=element_text(size=10),legend.key.size=unit(10,"pt"),legend.key.width=unit(26,"pt"),legend.position = "bottom",plot.title = element_text(size = 10))+geom_point(size=0.4)+scale_fill_manual(name = "Sc",labels=list.VariantType_1,values=c("#9ECAE1","#AE017E","#DE2D26"))+scale_color_manual(name = "Sc",labels=list.VariantType_1,values=c("#9ECAE1","#AE017E","#DE2D26"))+scale_x_continuous(expand=c(0,0),limits=c(1,16),breaks=c(2,seq(5,15,5)))+scale_y_continuous(expand=c(0,0),limits=c(0.02,0.08),breaks=seq(0.02,0.08,0.01))+geom_hline(yintercept=0,lty=2)+geom_ribbon(aes(ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(80))*100,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(80))*100),size=0,alpha=0.2)
fig5_goldenSM_corabs_mdac<-ggplot(data.list.goldenSM.corabs,aes(x=as.numeric(mdac),y=as.numeric(Mean)*100,group=VariantType,colour=factor(VariantType,levels=list.VariantType),fill=factor(VariantType,levels=list.VariantType)))+geom_line()+theme_classic()+labs(x="",y="LDcorabs (×100)",title="")+theme(text=element_text(family="serif",size=12),axis.text=element_text(size=10,color="black"),legend.text=element_text(size=10),legend.title=element_text(size=10),legend.key.size=unit(10,"pt"),legend.key.width=unit(26,"pt"),legend.position = "bottom",plot.title = element_text(size = 10))+geom_point(size=0.4)+scale_fill_manual(name = "Sc",labels=list.VariantType_1,values=c("#9ECAE1","#AE017E","#DE2D26"))+scale_color_manual(name = "Sc",labels=list.VariantType_1,values=c("#9ECAE1","#AE017E","#DE2D26"))+scale_x_continuous(expand=c(0,0),limits=c(1,16),breaks=c(2,seq(5,15,5)))+scale_y_continuous(expand=c(0,0),limits=c(0.11,0.17),breaks=seq(0.11,0.17,0.01))+geom_hline(yintercept=0,lty=2)+geom_ribbon(aes(ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(80))*100,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(80))*100),size=0,alpha=0.2)
fig5_panda_cor_mdac<-ggplot(data.list.panda.cor,aes(x=as.numeric(mdac),y=as.numeric(Mean)*100,group=VariantType,colour=factor(VariantType,levels=list.VariantType),fill=factor(VariantType,levels=list.VariantType)))+geom_line()+theme_classic()+labs(x=" ",y="",title="B.Panda")+theme(text=element_text(family="serif",size=12),axis.text=element_text(size=10,color="black"),legend.text=element_text(size=10),legend.title=element_text(size=10),legend.key.size=unit(10,"pt"),legend.position = "bottom",plot.title = element_text(size = 10))+geom_point(size=0.4)+scale_fill_manual(name = "Sc",labels=list.VariantType_1,values=c("#9ECAE1","#AE017E","#DE2D26"))+scale_color_manual(name = "Sc",labels=list.VariantType_1,values=c("#9ECAE1","#AE017E","#DE2D26"))+scale_x_continuous(expand=c(0,0),limits=c(1,16),breaks=c(2,seq(5,15,5)))+scale_y_continuous(expand=c(0,0),limits=c(0.03,0.15),breaks=seq(0.03,0.15,0.02))+geom_hline(yintercept=0,lty=2)+geom_ribbon(aes(ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(80))*100,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(80))*100),size=0,alpha=0.2)
fig5_panda_corabs_mdac<-ggplot(data.list.panda.corabs,aes(x=as.numeric(mdac),y=as.numeric(Mean)*100,group=VariantType,colour=factor(VariantType,levels=list.VariantType),fill=factor(VariantType,levels=list.VariantType)))+geom_line()+theme_classic()+labs(x="Max derived allele count",y="",title="")+theme(text=element_text(family="serif",size=12),axis.text=element_text(size=10,color="black"),legend.text=element_text(size=10),legend.title=element_text(size=10),legend.key.size=unit(10,"pt"),legend.position = "bottom",plot.title = element_text(size = 10))+geom_point(size=0.4)+scale_fill_manual(name = "Sc",labels=list.VariantType_1,values=c("#9ECAE1","#AE017E","#DE2D26"))+scale_color_manual(name = "Selection coefficient",labels=list.VariantType_1,values=c("#9ECAE1","#AE017E","#DE2D26"))+scale_x_continuous(expand=c(0,0),limits=c(1,16),breaks=c(2,seq(5,15,5)))+scale_y_continuous(expand=c(0,0),limits=c(0.14,0.26),breaks=seq(0.14,0.26,0.02))+geom_hline(yintercept=0,lty=2)+geom_ribbon(aes(ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(80))*100,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(80))*100),size=0,alpha=0.2)
fig5_pandaSim_cor_mdac<-ggplot(data.list.pandaSim.cor,aes(x=as.numeric(mdac),y=as.numeric(Mean)*100,group=VariantType,colour=factor(VariantType,levels=list.VariantType),fill=factor(VariantType,levels=list.VariantType)))+geom_point(size=0.4)+geom_line()+theme_classic()+labs(x="",y="",title="C.PandaSim")+theme(text=element_text(family="serif",size=12),axis.text=element_text(size=10,color="black"),legend.text=element_text(size=10),legend.title=element_text(size=10),legend.position = "bottom",legend.key.size=unit(10,"pt"),plot.title = element_text(size = 10))+scale_fill_manual(name = "Sc",labels=list.VariantType_1,values=c("#9ECAE1","#AE017E","#DE2D26"))+scale_color_manual(name = "Sc",labels=list.VariantType_1,values=c("#9ECAE1","#AE017E","#DE2D26"))+scale_x_continuous(expand=c(0,0),limits=c(1,16),breaks=c(2,seq(5,15,5)))+scale_y_continuous(expand=c(0,0),limits=c(0.3,1.2),breaks=seq(0.3,1.2,0.15))+geom_hline(yintercept=0,lty=2)+geom_ribbon(aes(ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(40))*100,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(40))*100),size=0,alpha=0.2)
fig5_pandaSim_corabs_mdac<-ggplot(data.list.pandaSim.corabs,aes(x=as.numeric(mdac),y=as.numeric(Mean)*100,group=VariantType,colour=factor(VariantType,levels=list.VariantType),fill=factor(VariantType,levels=list.VariantType)))+geom_point(size=0.4)+geom_line()+theme_classic()+labs(x="",y="",title="")+theme(text=element_text(family="serif",size=12),axis.text=element_text(size=10,color="black"),legend.text=element_text(size=10),legend.title=element_text(size=10),legend.position = "bottom",legend.key.size=unit(10,"pt"),plot.title = element_text(size = 10))+scale_fill_manual(name = "Sc",labels=list.VariantType_1,values=c("#9ECAE1","#AE017E","#DE2D26"))+scale_color_manual(name = "Sc",labels=list.VariantType_1,values=c("#9ECAE1","#AE017E","#DE2D26"))+scale_x_continuous(expand=c(0,0),limits=c(1,16),breaks=c(2,seq(5,15,5)))+scale_y_continuous(expand=c(0,0),limits=c(1.2,2.7),breaks=seq(1.2,2.7,0.25))+geom_hline(yintercept=0,lty=2)+geom_ribbon(aes(ymin=(as.numeric(Mean)-as.numeric(Sd)/sqrt(40))*100,ymax=(as.numeric(Mean)+as.numeric(Sd)/sqrt(40))*100),size=0,alpha=0.2)

fig5<-plot_grid(fig5_goldenSM_cor_mdac,fig5_panda_cor_mdac,fig5_pandaSim_cor_mdac,fig5_goldenSM_corabs_mdac,fig5_panda_corabs_mdac,fig5_pandaSim_corabs_mdac,ncol=3,align="vh")
ggsave("fig5.animal_sim.se.svg",fig5,width = 9, height = 6)

